{"uid":"c5af12a69e9983b7","name":"test_smoke","fullName":"tests.integration.test_smoke#test_smoke","historyId":"78ffebf457376473b3476ee0f7a454c9","time":{"start":1724980902441,"stop":1724982119025,"duration":1216584},"description":"Deploy bundle with app and release as a product.","descriptionHtml":"<p>Deploy bundle with app and release as a product.</p>\n","status":"broken","statusMessage":"asyncio.exceptions.TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 129, in _block\n    await jasyncio.sleep(wait_period)\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 605, in sleep\n    return await future\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 456, in wait_for\n    return fut.result()\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 848, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 831, in _runtest_for\n    yield\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 879, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/tests/integration/test_smoke.py\", line 70, in test_smoke\n    await ensure_statuses(ops_test)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/tests/integration/test_smoke.py\", line 42, in ensure_statuses\n    await ops_test.model.block_until(\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 1046, in block_until\n    await utils.block_until(done,\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 130, in block_until\n    await jasyncio.shield(jasyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 458, in wait_for\n    raise exceptions.TimeoutError() from exc\nasyncio.exceptions.TimeoutError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1724980902305,"stop":1724980902305,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1724980902305,"stop":1724980902305,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1724980902305,"stop":1724980902440,"duration":135},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1724980902441,"stop":1724980902441,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Deploy bundle with app and release as a product.","status":"broken","statusMessage":"asyncio.exceptions.TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 129, in _block\n    await jasyncio.sleep(wait_period)\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 605, in sleep\n    return await future\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 456, in wait_for\n    return fut.result()\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 848, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 831, in _runtest_for\n    yield\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 879, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/tests/integration/test_smoke.py\", line 70, in test_smoke\n    await ensure_statuses(ops_test)\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/tests/integration/test_smoke.py\", line 42, in ensure_statuses\n    await ops_test.model.block_until(\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 1046, in block_until\n    await utils.block_until(done,\n  File \"/home/runner/work/mysql-bundle/mysql-bundle/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 130, in block_until\n    await jasyncio.shield(jasyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 458, in wait_for\n    raise exceptions.TimeoutError() from exc\nasyncio.exceptions.TimeoutError","steps":[],"attachments":[{"uid":"65e31b2b883b0e0e","name":"log","source":"65e31b2b883b0e0e.txt","type":"text/plain","size":31356}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1724982119060,"stop":1724982119060,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1724982119060,"stop":1724982124715,"duration":5655},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1724982124716,"stop":1724982124716,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1724982124716,"stop":1724982124716,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1724982124716,"stop":1724982124716,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"group(1)"},{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_smoke"},{"name":"host","value":"fv-az881-351"},{"name":"thread","value":"8780-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_smoke"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"301f1e1f4ef358d8","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":2,"skipped":0,"passed":22,"unknown":2,"total":28},"items":[{"uid":"7509be2640d92727","reportUrl":"../1133//#testresult/7509be2640d92727","status":"unknown","time":{}},{"uid":"6dab05146242bfe4","reportUrl":"../1131//#testresult/6dab05146242bfe4","status":"failed","statusDetails":"AssertionError: assert 'mysql-database' in ['information_schema', 'mysql', 'performance_schema', 'sys']","time":{"start":1724808125087,"stop":1724808680778,"duration":555691}},{"uid":"54ab95b0b3122fc","reportUrl":"../1129//#testresult/54ab95b0b3122fc","status":"passed","time":{"start":1724721691037,"stop":1724722456186,"duration":765149}},{"uid":"7d9348c6522dfb8a","reportUrl":"../1127//#testresult/7d9348c6522dfb8a","status":"passed","time":{"start":1724635284723,"stop":1724636039415,"duration":754692}},{"uid":"ae695ad53074e62","reportUrl":"../1125//#testresult/ae695ad53074e62","status":"passed","time":{"start":1724548952489,"stop":1724549744134,"duration":791645}},{"uid":"afa9c684ed582718","reportUrl":"../1123//#testresult/afa9c684ed582718","status":"passed","time":{"start":1724462490014,"stop":1724463108325,"duration":618311}},{"uid":"19bb3f5c7caf0137","reportUrl":"../1120//#testresult/19bb3f5c7caf0137","status":"passed","time":{"start":1724376126289,"stop":1724376888220,"duration":761931}},{"uid":"dd94016e846f353c","reportUrl":"../1117//#testresult/dd94016e846f353c","status":"passed","time":{"start":1724289694075,"stop":1724290419704,"duration":725629}},{"uid":"2445a749070be755","reportUrl":"../1114//#testresult/2445a749070be755","status":"passed","time":{"start":1724203298209,"stop":1724204063555,"duration":765346}},{"uid":"1fe4e4a783800b50","reportUrl":"../1108//#testresult/1fe4e4a783800b50","status":"passed","time":{"start":1724116897340,"stop":1724117620253,"duration":722913}},{"uid":"37b87dd41c72bc81","reportUrl":"../1104//#testresult/37b87dd41c72bc81","status":"passed","time":{"start":1724030490657,"stop":1724031115473,"duration":624816}},{"uid":"efa4b5fe765b721b","reportUrl":"../1102//#testresult/efa4b5fe765b721b","status":"passed","time":{"start":1723944101707,"stop":1723944812753,"duration":711046}},{"uid":"cab90b6d37b5151c","reportUrl":"../1100//#testresult/cab90b6d37b5151c","status":"passed","time":{"start":1723857716577,"stop":1723858403250,"duration":686673}},{"uid":"26c49ff33717f7ff","reportUrl":"../1096//#testresult/26c49ff33717f7ff","status":"passed","time":{"start":1723771306180,"stop":1723772051132,"duration":744952}},{"uid":"642c5c1acc72759c","reportUrl":"../1094//#testresult/642c5c1acc72759c","status":"passed","time":{"start":1723684872618,"stop":1723685555162,"duration":682544}},{"uid":"ec31e8581c82fd8f","reportUrl":"../1091//#testresult/ec31e8581c82fd8f","status":"passed","time":{"start":1723598762350,"stop":1723599406631,"duration":644281}},{"uid":"eff64d3eea7cb3be","reportUrl":"../1089//#testresult/eff64d3eea7cb3be","status":"failed","statusDetails":"AssertionError: assert 'mysql-database' in ['information_schema', 'mysql', 'performance_schema', 'sys']","time":{"start":1723512631013,"stop":1723513259730,"duration":628717}},{"uid":"cbb7e9d1a36b94f3","reportUrl":"../1087//#testresult/cbb7e9d1a36b94f3","status":"passed","time":{"start":1723425777714,"stop":1723426556111,"duration":778397}},{"uid":"30f4863c369482e8","reportUrl":"../1085//#testresult/30f4863c369482e8","status":"passed","time":{"start":1723339430519,"stop":1723340171480,"duration":740961}},{"uid":"8ae33e7a6b983442","reportUrl":"../1083//#testresult/8ae33e7a6b983442","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1723252960374,"stop":1723254178012,"duration":1217638}}]},"tags":["asyncio","abort_on_fail","group(1)"]},"source":"c5af12a69e9983b7.json","parameterValues":[]}